### PR TITLE
add initial data structures

### PR DESCRIPTION
**Pull request by Dylan-Floyd**

### CODE REVIEW

**Review by yosefkirkcohen — COMMENTED** [review]
This is astonishing

**Review by diyanamendoza — APPROVED** [review]
w00t

**Comment by Dylan-Floyd** [comment]
🎉

**Review by MikepdXRider — COMMENTED** [review]
🥇

**Review by MikepdXRider — APPROVED** [review]

**Review by yosefkirkcohen — APPROVED** [review]

**Pull request merged**
